### ISSUE TITLE
HM-06 working HM-10 not

### ISSUE THREAD

**Issue by matthewric** [rabee2050/Arduino-Bluetooth-Kit-V2#1]
Hello I tried this with a HM-10 did not work same wiring on a HM-06 worked the HM-10 is detected in BLE but fails to connect however the light on the HM-10 goes solid. The arduino uses is a 5v nano

**Comment by rabee2050** [comment]
the app have been tested with Hc-06 and Adafruit modules only, hopefully in the future we will support all modules.
